#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# KAT — Judge0 CE (code execution engine) setup script
#
# Run on a fresh Ubuntu 22.04 KVM-based VPS as root (or with sudo).
# ⚠  Does NOT work on OpenVZ / LXC VPS — isolate needs Linux namespaces.
#
# Usage:
#   chmod +x judge0-setup.sh
#   sudo ./judge0-setup.sh
#
# You will be prompted for:
#   DOMAIN   — subdomain pointing to this VPS, e.g. code.yourdomain.com
#   EMAIL    — for Let's Encrypt TLS certificate
#
# After the script completes it prints the values you need to add to Vercel.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
log()  { echo -e "${GREEN}►${NC} $*"; }
warn() { echo -e "${YELLOW}⚠${NC}  $*"; }
die()  { echo -e "${RED}✖${NC}  $*"; exit 1; }

[[ "$EUID" -ne 0 ]] && die "Please run as root: sudo ./judge0-setup.sh"

# ── 0. Gather config ──────────────────────────────────────────────────────────
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  KAT — Judge0 CE installer"
echo "═══════════════════════════════════════════════════════════"
echo ""

read -rp "Judge0 domain (e.g. code.yourdomain.com): " DOMAIN
[[ -z "$DOMAIN" ]] && die "DOMAIN is required."

read -rp "Email for Let's Encrypt TLS:              " EMAIL
[[ -z "$EMAIL" ]] && die "EMAIL is required."

# Generate secrets
POSTGRES_PASSWORD=$(openssl rand -hex 24)
REDIS_PASSWORD=$(openssl rand -hex 24)
AUTHN_TOKEN=$(openssl rand -hex 32)

INSTALL_DIR="/opt/judge0"

echo ""
log "Starting Judge0 CE installation on $DOMAIN …"
echo ""

# ── 1. Verify this is a KVM-based host ───────────────────────────────────────
log "Checking virtualisation type …"
VIRT=$(systemd-detect-virt 2>/dev/null || echo "unknown")
if [[ "$VIRT" == "openvz" || "$VIRT" == "lxc" ]]; then
  die "Detected $VIRT container — Judge0 isolate requires KVM-based virtualisation. Use Hetzner CX, DigitalOcean Droplet, Linode, etc."
fi
log "Virtualisation: $VIRT (OK)"

# ── 2. System prep ────────────────────────────────────────────────────────────
log "Updating system packages …"
apt-get update -y
apt-get upgrade -y
apt-get install -y \
  curl wget gnupg2 apt-transport-https ca-certificates \
  software-properties-common lsb-release nginx certbot \
  python3-certbot-nginx openssl net-tools

# ── 3. Install Docker Engine ──────────────────────────────────────────────────
log "Installing Docker Engine …"
if ! command -v docker &>/dev/null; then
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    | gpg --dearmor -o /usr/share/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker.gpg] \
    https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  systemctl enable docker
  systemctl start docker
  log "Docker installed: $(docker --version)"
else
  log "Docker already installed: $(docker --version)"
fi

# Ensure the compose plugin is available
docker compose version &>/dev/null || die "Docker Compose plugin not found. Run: apt-get install -y docker-compose-plugin"

# ── 4. Create install directory ───────────────────────────────────────────────
log "Creating $INSTALL_DIR …"
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

# ── 5. Write judge0.conf ──────────────────────────────────────────────────────
log "Writing $INSTALL_DIR/judge0.conf …"
cat > "$INSTALL_DIR/judge0.conf" <<CONF
################################################################################
# Judge0 CE — configuration
# Generated by KAT judge0-setup.sh on $(date)
################################################################################

# ── PostgreSQL ──────────────────────────────────────────────────────────────
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_HOST=db
POSTGRES_PORT=5432

# ── Redis ────────────────────────────────────────────────────────────────────
REDIS_PASSWORD=${REDIS_PASSWORD}
# Judge0 reads host/port separately (not REDIS_URL) — must point to the redis service
REDIS_HOST=redis
REDIS_PORT=6379

# ── Authentication ───────────────────────────────────────────────────────────
# Judge0 checks this header on every API request.
# Set AUTHN_TOKEN to a strong secret; leave blank to disable auth (not recommended).
AUTHN_HEADER=X-Auth-Token
AUTHN_TOKEN=${AUTHN_TOKEN}

# ── Workers ──────────────────────────────────────────────────────────────────
# Number of concurrent job workers. Match to your vCPU count.
WORKERS_COUNT=2

# ── Execution limits (global maximums — per-submission limits can be lower) ──
# CPU time in seconds a submission may use
MAX_CPU_TIME_LIMIT=10
# Wall-clock time (includes I/O wait) in seconds
MAX_WALL_TIME_LIMIT=20
# Memory in kilobytes (256 MB)
MAX_MEMORY_LIMIT=262144
# Stack size in KB
MAX_STACK_LIMIT=65536
# Processes/threads per submission
MAX_MAX_PROCESSES_AND_OR_THREADS=60
# Output size in KB
MAX_MAX_FILE_SIZE=4096
# Number of runs (reserved for future use)
NUMBER_OF_RUNS=1

# ── Per-process limits ───────────────────────────────────────────────────────
# These must be true so Judge0 runs isolate WITHOUT --cg (cgroup v1 flag).
# cgroup v1 memory controller is absent on most modern Ubuntu hosts (cgroup v2).
# Keeping these true avoids "Failed to create control group" sandbox errors.
ALLOW_ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT=true
ALLOW_ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT=true

# ── Defaults applied when a submission does not specify its own limits ────────
CPU_TIME_LIMIT=5
WALL_TIME_LIMIT=10
MEMORY_LIMIT=131072
STACK_LIMIT=65536
MAX_PROCESSES_AND_OR_THREADS=60
ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT=true
ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT=true
MAX_FILE_SIZE=1024

# ── Submission behaviour ─────────────────────────────────────────────────────
# Return result synchronously (no client-side polling needed)
ENABLE_WAIT_RESULT=true
# Cache submission results for this many seconds (0 = disabled)
SUBMISSION_CACHE_DURATION=1

# ── Rails internal ────────────────────────────────────────────────────────────
RAILS_ENV=production
SECRET_KEY_BASE=$(openssl rand -hex 64)
CONF

chmod 644 "$INSTALL_DIR/judge0.conf"

# ── 6. Write docker-compose.yml ───────────────────────────────────────────────
log "Writing $INSTALL_DIR/docker-compose.yml …"
cat > "$INSTALL_DIR/docker-compose.yml" <<'COMPOSE'
services:

  server:
    image: judge0/judge0:1.13.1
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    env_file: judge0.conf
    ports:
      - "127.0.0.1:2358:2358"   # bind to loopback only — Nginx proxies externally
    privileged: true
    restart: always
    depends_on:
      - db
      - redis

  workers:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    env_file: judge0.conf
    privileged: true
    restart: always
    depends_on:
      - db
      - redis

  db:
    image: postgres:16.0
    env_file: judge0.conf
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    restart: always

  redis:
    image: redis:7.2.1
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    restart: always

volumes:
  postgres-data:
COMPOSE

# ── 7. Pull images and start DB + Redis first ─────────────────────────────────
log "Pulling Docker images (this may take a few minutes) …"
cd "$INSTALL_DIR"
docker compose pull

log "Starting db and redis …"
docker compose up -d db redis
log "Waiting 15 s for Postgres to initialise …"
sleep 15

# ── 8. Start the full stack ───────────────────────────────────────────────────
log "Starting Judge0 server and workers …"
docker compose up -d
log "Waiting 20 s for Judge0 to run DB migrations …"
sleep 20

# Re-up to ensure all services are healthy after migrations
docker compose up -d

# ── 9. Configure firewall ─────────────────────────────────────────────────────
log "Configuring firewall …"
if command -v ufw &>/dev/null; then
  ufw allow 22/tcp
  ufw allow 80/tcp
  ufw allow 443/tcp
  # Port 2358 is bound to 127.0.0.1 only — no need to open it externally
  ufw --force enable
  log "Firewall: 22, 80, 443 open. Port 2358 restricted to loopback."
fi

# ── 10. Configure Nginx as reverse proxy ──────────────────────────────────────
log "Writing Nginx config for $DOMAIN …"
cat > "/etc/nginx/sites-available/judge0" <<NGINX
server {
    listen 80;
    server_name ${DOMAIN};

    # Let's Encrypt challenge
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name ${DOMAIN};

    ssl_certificate     /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    client_max_body_size 10M;

    location / {
        proxy_pass         http://127.0.0.1:2358;
        proxy_http_version 1.1;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_read_timeout 60s;
    }
}
NGINX

ln -sf /etc/nginx/sites-available/judge0 /etc/nginx/sites-enabled/judge0
rm -f /etc/nginx/sites-enabled/default

# ── 11. Obtain Let's Encrypt TLS certificate ──────────────────────────────────
log "Obtaining Let's Encrypt certificate for $DOMAIN …"
# Serve HTTP temporarily for challenge
nginx -t && systemctl reload nginx || systemctl start nginx

certbot certonly --nginx \
  --non-interactive \
  --agree-tos \
  --email "$EMAIL" \
  -d "$DOMAIN"

# ── 12. Enable Nginx with TLS and reload ──────────────────────────────────────
nginx -t
systemctl enable nginx
systemctl reload nginx

# ── 13. Verify Judge0 API ─────────────────────────────────────────────────────
echo ""
log "Verifying Judge0 health endpoint …"
sleep 5
HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
  -H "X-Auth-Token: ${AUTHN_TOKEN}" \
  "https://${DOMAIN}/system_info" 2>/dev/null || echo "000")

if [[ "$HTTP_STATUS" == "200" ]]; then
  log "Judge0 API is UP (HTTP $HTTP_STATUS)"
else
  warn "Health check returned HTTP $HTTP_STATUS — services may still be starting."
  warn "Check: docker compose -f $INSTALL_DIR/docker-compose.yml logs server"
fi

# ── 14. Service status ────────────────────────────────────────────────────────
echo ""
log "Docker service status:"
docker compose -f "$INSTALL_DIR/docker-compose.yml" ps

# ── 15. Summary ───────────────────────────────────────────────────────────────
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "  Installation COMPLETE"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "  DOMAIN:          $DOMAIN"
echo "  AUTHN_TOKEN:     $AUTHN_TOKEN"
echo "  API URL:         https://$DOMAIN"
echo ""
echo "  ⚠  Add these to Vercel environment variables:"
echo "     JUDGE0_API_URL=https://$DOMAIN"
echo "     JUDGE0_API_KEY=$AUTHN_TOKEN"
echo ""
echo "  Useful commands on the VPS:"
echo "    docker compose -f $INSTALL_DIR/docker-compose.yml ps"
echo "    docker compose -f $INSTALL_DIR/docker-compose.yml logs -f server"
echo "    docker compose -f $INSTALL_DIR/docker-compose.yml logs -f workers"
echo "    docker compose -f $INSTALL_DIR/docker-compose.yml restart"
echo ""
echo "  Test the API:"
echo "    curl -H 'X-Auth-Token: $AUTHN_TOKEN' https://$DOMAIN/system_info"
echo ""
echo "  Submit code (example — Python 3 = language_id 71):"
echo "    curl -X POST https://$DOMAIN/submissions \\"
echo "      -H 'X-Auth-Token: $AUTHN_TOKEN' \\"
echo "      -H 'Content-Type: application/json' \\"
echo "      -d '{\"source_code\":\"print(\\\"hello\\\"))\",\"language_id\":71,\"stdin\":\"\"}'"
echo "═══════════════════════════════════════════════════════════════════"

# Save credentials
CREDS_FILE="/home/${SUDO_USER:-root}/kat-judge0-credentials.txt"
cat > "$CREDS_FILE" <<CREDS
# KAT Judge0 CE Credentials — generated $(date)
# Add to Vercel environment variables:

JUDGE0_API_URL=https://${DOMAIN}
JUDGE0_API_KEY=${AUTHN_TOKEN}

# Internal secrets (stored in /opt/judge0/judge0.conf — do not expose):
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
REDIS_PASSWORD=${REDIS_PASSWORD}
CREDS
chmod 600 "$CREDS_FILE"
log "Credentials saved to $CREDS_FILE"
